
language: cpp

compiler:
  - clang
  - gcc

install:
    - echo "deb http://mirrors.kernel.org/ubuntu/ vivid universe" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get install python3-dev
    - sudo apt-get install cmake=3.0.2-1ubuntu2
    - cmake --version

before_script:
  - cd reformulation
  - wget https://github.com/Attempto/Clex/blob/master/clex_lexicon.pl?raw=true
  - mkdir build
  - cd build/
  - cmake ..

script:
  - make reformulation
  
