
language: cpp

compiler:
  - clang
  - gcc

install:
    - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install python3-dev
    - cmake --version
    - sudo apt-get install cmake
    - cmake --version

before_script:
  - cd reformulation
  - wget https://github.com/Attempto/Clex/blob/master/clex_lexicon.pl?raw=true
  - mkdir build
  - cd build/
  - cmake ..

script:
  - make reformulation
  
