
language: cpp

compiler:
  - clang
  - gcc

install:
    - sudo apt-get install python3-dev

before_script:
  - cd reformulation
  - wget https://github.com/Attempto/Clex/blob/master/clex_lexicon.pl?raw=true
  - mkdir build
  - cd build/
  - cmake ..

script:
  - make reformulation
  
