#ifndef DEFINITIONS_H
#define DEFINITIONS_H


#define NOTINFINITERECONSTRUCTIONFACTOR 1.5f //should be 1 if ideal case
#define WORDSIZE 50
#define MERGESIZE 6*3*WORDSIZE*WORDSIZE
#define COMPACTSIZE 3*WORDSIZE*WORDSIZE
#define UNCOMPACTSIZE 3*WORDSIZE*WORDSIZE


typedef std::vector<float> word;

#endif